- examples/colorizer.py
- hypergan/cli.py
- hypergan/config.py
- hypergan/discriminators/densenet_discriminator.py
- hypergan/discriminators/pyramid_nostride_discriminator.py
- hypergan/gan.py
- hypergan/generators/dense_resize_conv.py
- hypergan/graph/graph.py
- hypergan/samplers/progressive_enhancement_sampler.py
- hypergan/trainers/__init__.py
- hypergan/trainers/adam_trainer.py
- hypergan/trainers/rmsprop_trainer.py
- hypergan/trainers/wgan_trainer.py
- hypergan/util/gan_server.py
- hypergan/util/ops.py
https://www.reddit.com/r/MachineLearning/comments/5qxoaz/r_170107875_wasserstein_gan/?st=iyjqdgqo&sh=9239f664
Attempt at wgan
> [wip] wgan implementation attempt

- hypergan/config.py
- hypergan/encoders/categories_encoder.py
- hypergan/graph/graph.py
- hypergan/losses/category.py
Moves categorical InfoGAN into new structure:
1. Category Encoder - adds to z_base 
2. Category Loss - adds the optional loss terms
I still need to think how sampling works with this.
> Categories refactor

- README.md
Adding more documentation.  It'd be nice to autogenerate docs, but I think just writing things down in README is easier for now.
> API docs 0.8

- hypergan/cli.py
Adds the ability for CLI to enter a python shell by pressing return any time during training.
flag is `--ipython True`
> --ipython for command line

- examples/colorizer.py
- hypergan/cli.py
- hypergan/discriminators/densenet_discriminator.py
- hypergan/discriminators/densenet_weighted_discriminator.py
- hypergan/discriminators/fast_strided_discriminator.py
- hypergan/discriminators/minibatch_discriminator.py
- hypergan/discriminators/painters_discriminator.py
- hypergan/discriminators/pyramid_discriminator.py
- hypergan/encoders/categories_encoder.py
- hypergan/encoders/linear_encoder.py
- hypergan/gan.py
- hypergan/generators/dense_resize_conv_generator.py
- hypergan/generators/resize_conv_generator.py
- hypergan/graph/graph.py
- hypergan/losses/category_loss.py
- hypergan/losses/standard_gan_loss.py
- hypergan/losses/supervised_loss.py
- hypergan/util/hc_tf.py
- hypergan/util/ops.py
- hypergan/util/wavegan.py
- hypergan/vendor/vggnet_loader.py
- hypergan/vendor/wavenet.py
- requirements.txt
Used https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/compatibility/tf_upgrade.py
> Tensorflow 1.0 support

- README.md
- examples/2d-measure-accuracy.py
- examples/2d-test.py
- examples/Readme.md
- examples/gd-optimizer.py
- hypergan/cli.py
- hypergan/config.py
- hypergan/discriminators/pyramid_discriminator.py
- hypergan/encoders/linear_encoder.py
- hypergan/gan.py
- hypergan/generators/inception_generator.py
- hypergan/generators/resize_conv_generator.py
- hypergan/graph/graph.py
- hypergan/losses/lamb_gan_loss.py
- hypergan/losses/standard_gan_loss.py
- hypergan/trainers/adam_trainer.py
- hypergan/trainers/common.py
- hypergan/trainers/momentum_trainer.py
- hypergan/trainers/rmsprop_d_adam_g_trainer.py
- hypergan/trainers/rmsprop_trainer.py
- hypergan/trainers/sgd_adam_trainer.py
- hypergan/trainers/sgd_trainer.py
See how a very simple gans fits a 2d probability distribution.
> 2d test example

- examples/2d-measure-accuracy.py
- hypergan/gan.py
- hypergan/graph/graph.py
- hypergan/losses/lamb_gan_loss.py
- hypergan/losses/lsgan_loss.py
- hypergan/losses/wgan_loss.py
- hypergan/trainers/sgd_trainer.py
https://arxiv.org/pdf/1611.04076v2.pdf
New loss function.  
D <- (d_real - b)**2 + (d_fake - a)**2
G <- (d_fake - c)**2
Compatible with all other loss functions and architectures.
> LS-GAN loss function implementation

- hypergan/generators/resize_conv_generator.py
> fixes single channel support, #56

- examples/2d-measure-accuracy.py
- hypergan/trainers/any_trainer.py
any_trainer will be able to start any optimizer combination for easier hyperparam search.
It is missing a few right now:
```python
```
> [feature] any_trainer - combines rmsprop, adagrad, adadelta, sgd

- examples/2d-measure-accuracy.py
- examples/2d-test.py
- hypergan/discriminators/pyramid_discriminator.py
- hypergan/generators/resize_conv_cheap_generator.py
- hypergan/generators/resize_conv_generator.py
- hypergan/trainers/any_trainer.py
- hypergan/util/hc_tf.py
- hypergan/util/ops.py
Attempt to increase the network depth capacity of both the Discriminator and Generator.
Inspired by https://arxiv.org/pdf/1702.08591.pdf
> Orthogonal initialization

- examples/static-batch-test.py
- hypergan/cli.py
- hypergan/discriminators/pyramid_discriminator.py
- hypergan/gan.py
- hypergan/generators/common.py
- hypergan/generators/resize_conv_generator.py
- hypergan/trainers/any_trainer.py
- hypergan/util/hc_tf.py
- hypergan/util/ops.py
New automated search for g/d combinations (like 2d-measure-accuracy).
Add more hyperparams to control batch norm.
> Static batch test

- hypergan/generators/dts_generator.py
This branch attempt to replace the `resize_images` call with `depth_to_space`.
> Depth to space generator

- hypergan/losses/began_h_loss.py
- hypergan/samplers/began_sampler.py
Some hacks.  Merging into main align-began branch.
> Aligned began experiment 2

- README.md
This would have helped me when I was starting out. :)
> Document how to use virtualenv and install HyperGAN's dependencies.

- hypergan/losses/softmax_loss.py
Softmax gan loss(working)
https://arxiv.org/abs/1704.06191
> Softmax gan

- hypergan/search/random_search.py
Expands the random search options.
> Expanded search space

- hypergan/cli.py
- hypergan/discriminators/cramer_discriminator.py
- hypergan/graph/graph.py
- hypergan/losses/cramer_loss.py
- hypergan/search/random_search.py
New loss function.
https://arxiv.org/pdf/1705.10743.pdf
Remaining:
>  Cramér GAN

- Changelog.md
- README.md
Extract changelog.md.  Move showcase and about up.
> Rearrange README

- CONTRIBUTING.md
- README.md
Adds a CONTRIBUTING.md as per github standards(and to help guide anyone looking to contribute).
https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
Not adding the code of conduct.  If you are interested in contributing or using hypergan we welcome you.
> Initial contribution guide

- hypergan/cli.py
Outputs to "builds/#{config}.pbgraph"
> hypergan build

- hypergan/trainers/alternating_trainer.py
- hypergan/trainers/base_trainer.py
- hypergan/trainers/multi_step_trainer.py
Implements various training rate decay functions.  Example:
```json
"trainer" : {
"decay_function": "function:tensorflow.python.training.learning_rate_decay.exponential_decay",
"decay_steps": 100000,
"decay_rate": 0.96
}
```
> Learning rate decay functions

- hypergan/samplers/began_sampler.py
Adds began sampling to the debug sampler (`-sampler debug`)
> Debug sampler - BEGAN

- hypergan/trainers/alternating_trainer.py
- hypergan/trainers/base_trainer.py
- hypergan/trainers/multi_step_trainer.py
Reverts 255BITS/HyperGAN#137
Breaks 0.9 graph.
> Revert "Learning rate decay functions"

- hypergan/trainers/alternating_trainer.py
- hypergan/trainers/base_trainer.py
- hypergan/trainers/multi_step_trainer.py
> Decay functions

- hypergan/gans/alpha_gan.py
- hypergan/losses/base_loss.py
Implements gradient_locally_stable configuration option.  Added to BaseLoss so it works with all losses.
https://arxiv.org/pdf/1706.04156.pdf
Status: running, searching for config
> Gradient descent GAN optimization is locally stable

- hypergan/__init__.py
- hypergan/cli.py
- hypergan/configurations/__init__.py
- hypergan/discriminators/__init__.py
- hypergan/encoders/__init__.py
- hypergan/gans/__init__.py
- hypergan/gans/alpha_gan.py
- hypergan/generators/__init__.py
- hypergan/generators/base_generator.py
- hypergan/inputs/__init__.py
- hypergan/losses/__init__.py
- hypergan/ops/__init__.py
- hypergan/ops/tensorflow/__init__.py
- hypergan/samplers/__init__.py
- hypergan/search/__init__.py
- hypergan/trainers/__init__.py
This branch is just improving to the source code comments for the api documentation.
> Source code comments

- GettingStarted.md
Getting started document for new users.
Remaining:
> Getting started

- hypergan/configurations/fgan-gan.json
- hypergan/configurations/fgan-js.json
- hypergan/configurations/fgan-pearson.json
- hypergan/configurations/fgan-reverse_kl.json
- hypergan/losses/f_divergence_loss.py
f-GAN: Training Generative Neural Samplers using Variational Divergence Minimization
Implementation of https://arxiv.org/abs/1606.00709
Example:
```
"loss" : {
"class" : "class:hypergan.losses.f_divergence_loss.FDivergenceLoss",
"type": "kl"
}
```
Types are:
* `kl` - Kullback Leibler divergence
* `reverse_kl` - Reverse Kullback Leibler divergence
* `js` - Jensen - Shannon divergence
* `gan` - original formulation
* `pearson` - Pearson distance
* `squared_hellinger` - Squared Hellinger distace
Works(well) with gradient penalty.
> f-GAN: Training Generative Neural Samplers using Variational Divergence Minimization

- hypergan/cli.py
- hypergan/configurations/alpha-default-tiny.json
- hypergan/discriminators/base_discriminator.py
- hypergan/discriminators/cramer_discriminator.py
- hypergan/discriminators/fully_connected_discriminator.py
- hypergan/encoders/base_encoder.py
- hypergan/encoders/uniform_encoder.py
- hypergan/gan_component.py
- hypergan/gans/alpha_gan.py
- hypergan/gans/base_gan.py
- hypergan/gans/multi_generator_gan.py
- hypergan/gans/standard_gan.py
- hypergan/generators/base_generator.py
- hypergan/generators/multisegment_generator.py
- hypergan/generators/resize_conv_generator.py
- hypergan/generators/segment_generator.py
- hypergan/losses/base_loss.py
- hypergan/losses/vral_loss.py
- hypergan/multi_component.py
- hypergan/ops/tensorflow/ops.py
- hypergan/samplers/alphagan_random_walk_sampler.py
- hypergan/samplers/batch_sampler.py
- hypergan/samplers/segment_sampler.py
- hypergan/samplers/static_batch_sampler.py
- hypergan/trainers/alternating_trainer.py
- hypergan/trainers/base_trainer.py
- hypergan/trainers/multi_step_trainer.py
Usability improvements to the API:
*  Remove the need to call `GANComponent.create()` explicitly after construction.
*  Refactor αGAN for readability and maintainability.
> Refactor object lifecycle

- README.md
- examples/next-frame.py
- hypergan/configurable_component.py
- hypergan/optimizers/giga_wolf_optimizer.py
- hypergan/optimizers/predictive_method_optimizer.py
- hypergan/samplers/debug_sampler.py
- hypergan/train_hooks/gp_sn_memory_train_hook.py
- hypergan/train_hooks/memory_train_hook.py
- hypergan/train_hooks/weight_constraint_train_hook.py
- hypergan/trainers/depth_trainer.py
- hypergan/trainers/qualified_step_trainer.py
- hypergan/trainers/simultaneous_trainer.py
Fixes and enhancements for 0.10.  Contains:
* Updated Documentation
* Cleanup and refactoring
* New Trainers/Optimizers
> 0.10 Alpha 2

- bin/hypergan
- examples/next-frame.py
- hypergan/cli.py
- hypergan/gans/ali_gan.py
- hypergan/pygame_viewer.py
- hypergan/trainers/fitness_trainer.py
- hypergan/trainers/gang_trainer.py
> 0.10 alpha 4

- README.md
- examples/chargan.py
- examples/next-frame.py
- hypergan/cli.py
- hypergan/configurable_component.py
- hypergan/gan_component.py
- hypergan/gans/ali_gan.py
- hypergan/gans/base_gan.py
- hypergan/gans/standard_gan.py
- hypergan/generators/base_generator.py
- hypergan/inputs/image_loader.py
- hypergan/inputs/multi_image_loader.py
- hypergan/optimizers/curl_optimizer.py
- hypergan/optimizers/elastic_weight_consolidation_optimizer.py
- hypergan/optimizers/giga_wolf_optimizer.py
- hypergan/samplers/batch_walk_sampler.py
- hypergan/samplers/static_batch_sampler.py
- hypergan/train_hooks/imle_train_hook.py
- hypergan/train_hooks/progress_compress_train_hook.py
- hypergan/train_hooks/self_supervised_train_hook.py
- hypergan/train_hooks/weight_constraint_train_hook.py
- hypergan/trainers/alternating_trainer.py
- json.md
- tutorial1.md
Stabilizing on batch size 1
New in alpha 6:
* Progress/Compress train hook (adds a daytime nighttime cycle with knowledge base)
* Online Elastic Weight Consolidation optimizer
* IMLE train hook
* Various bug fixes and documentation updates
> 0.10 alpha 6

- README.md
- hypergan/gans/alpha_gan.py
- hypergan/losses/base_loss.py
- hypergan/train_hooks/progress_compress_kbgan_train_hook.py
- tests/cli_test.py
- tests/gan_component_test.py
- tests/gan_test.py
- tests/mocks.py
- tests/multi_component_test.py
- tutorial1.md
Better documentation, fixing unit tests, new method for training progress-compress knowledge base.
> 0.10 alpha 7

- hypergan/configurable_component.py
- hypergan/gan_component.py
- hypergan/generators/resizeable_generator.py
- hypergan/optimizers/elastic_weight_consolidation_optimizer.py
- json.md
Feature: 2 new layers for working with images that aren't a power of two: `resize_images` and `crop`
> 0.10 alpha 11

- hypergan/cli.py
- hypergan/configurable_component.py
- hypergan/configurations/colorizer-64x64.json
- hypergan/gans/base_gan.py
- hypergan/gans/standard_gan.py
- hypergan/optimizers/curl_optimizer.py
- hypergan/optimizers/elastic_weight_consolidation_optimizer.py
- hypergan/optimizers/giga_wolf_optimizer.py
- hypergan/tk_viewer.py
- hypergan/train_hooks/gradient_penalty_train_hook.py
Changes:
* New colorizer example configuration
* Fixes for tk resizing events
* Add a status bar to the tk interface
* `hypergan build` now uses tflite(requires tf 2.0, hg is still compatible with older tf versions)
* Adds warning if variables are defined but not included in save
> 0.10 alpha 16

- README.md
- bin/hypergan
- hypergan/cli.py
- hypergan/gans/ali_vib_gan.py
- hypergan/tk_viewer.py
- requirements.txt
Another alpha release.
* Adds `hypergan test` to test install
* Remove old pygame resize code as it may have been causing crash
* Add missing `nashpy` requirement
* Menu keyboard shortcuts
> 0.10 alpha 17

- bin/hypergan
- circle.yml
- examples/colorizer.py
- examples/common.py
- hypergan/cli.py
- hypergan/configuration.py
- hypergan/configurations/default-ali.json
- hypergan/configurations/default.json
- hypergan/gans/ali_gan.py
- hypergan/gans/base_gan.py
- hypergan/gans/standard_gan.py
- hypergan/generators/resizable_generator.py
- hypergan/generators/segment_generator.py
- hypergan/samplers/grid_sampler.py
- hypergan/tk_viewer.py
- tests/discriminators/autoencoder_discriminator_test.py
- tests/discriminators/cramer_discriminator_test.py
- tests/discriminators/pyramid_discriminator_test.py
- tests/gan_test.py
- tests/gans/base_gan_test.py
- tests/gans/standard_gan_test.py
- tests/generators/align_generator_test.py
- tests/generators/resizable_generator_test.py
- tests/inputs/image_loader_test.py
- tests/losses/category_loss_test.py
- tests/losses/cramer_loss_test.py
- tests/samplers/grid_sampler_test.py
* Usability: better error message when configuration not found
* Usability: prevent training model when no save is possible
* Test fixes
* examples/colorizer build
> 0.10 alpha 18

- hypergan/cli.py
- hypergan/configurations/gang.json
- hypergan/configurations/progress-compress.json
- hypergan/losses/ali_loss.py
- hypergan/losses/logistic_loss.py
- hypergan/samplers/aligned_sampler.py
- hypergan/samplers/base_sampler.py
- hypergan/samplers/batch_walk_sampler.py
- hypergan/samplers/gang_sampler.py
- hypergan/samplers/static_batch_sampler.py
- hypergan/tk_viewer.py
- hypergan/trainers/gang_trainer.py
Includes:
* Logistic Loss
* tk 'Sample' menu
* Configurations for 'progress-compress' and 'gang' evolutionary trainer
> 0.10 alpha 20

- bin/hypergan
- hypergan/cli.py
just save losses graphs like this
https://imgur.com/a/jX3VwMK
my code can save more than 2 loss types,so its compatible with alphagan and other configurations that have more than 2 losses...
> Save losses graphs

- requirements.txt
A simple commit that add tensorflow-gan to requirements.txt
> Add TF-GAN on requirement.txt

- bin/hypergan
- hypergan/cli.py
- hypergan/configuration.py
- hypergan/configurations/colorizer.json
- hypergan/configurations/default.json
Improves the default configuration.
[![Training video](https://img.youtube.com/vi/0Y4d4pknytA/0.jpg)](https://www.youtube.com/watch?v=0Y4d4pknytA)
1.0 RC1 default configuration is too small. This increases the size.
Also prevent loading from packaged configuration directory. This enforces the use of `hypergan new [config]` before `hypergan train [dataset] -c [config]`
> Better default configuration

- hypergan/backends/cpu_backend.py
- hypergan/gans/base_gan.py
- hypergan/trainable_gan.py
Adds a CPU backend `-B cpu`
Useful for sampling. Training with cpu is not advised as it's far too slow.
> CPU backend
